#!/bin/bash

#######################################################
## This script clones 1000 most starred (as par Nov. ##
## 2019) Java projects in GitHub. 					 ##
#######################################################

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?

if [ $GIT_IS_AVAILABLE -gt 0 ]; then 
	echo 'Install `Git` and re-run the script...'
	exit 1
fi

mkdir -p Projects
cd Projects
rm -rf *

git clone https://github.com/elastic/elasticsearch.git 
git clone https://github.com/spring-projects/spring-boot.git 
git clone https://github.com/ReactiveX/RxJava.git 
git clone https://github.com/square/okhttp.git 
git clone https://github.com/google/guava.git 
git clone https://github.com/square/retrofit.git 
git clone https://github.com/spring-projects/spring-framework.git 
git clone https://github.com/apache/dubbo.git 
git clone https://github.com/PhilJay/MPAndroidChart.git 
git clone https://github.com/bumptech/glide.git 
git clone https://github.com/airbnb/lottie-android.git 
git clone https://github.com/Blankj/AndroidUtilCode.git 
git clone https://github.com/proxyee-down-org/proxyee-down.git 
git clone https://github.com/JakeWharton/butterknife.git 
git clone https://github.com/zxing/zxing.git 
git clone https://github.com/crossoverJie/JCSprout.git 
git clone https://github.com/greenrobot/EventBus.git 
git clone https://github.com/netty/netty.git 
git clone https://github.com/skylot/jadx.git 
git clone https://github.com/alibaba/fastjson.git 
git clone https://github.com/alibaba/p3c.git 
git clone https://github.com/CymChad/BaseRecyclerViewAdapterHelper.git 
git clone https://github.com/ReactiveX/RxAndroid.git 
git clone https://github.com/Netflix/Hystrix.git 
git clone https://github.com/ctripcorp/apollo.git 
git clone https://github.com/NationalSecurityAgency/ghidra.git 
git clone https://github.com/alibaba/arthas.git 
git clone https://github.com/square/picasso.git 
git clone https://github.com/google/gson.git 
git clone https://github.com/nostra13/Android-Universal-Image-Loader.git 
git clone https://github.com/hankcs/HanLP.git 
git clone https://github.com/chrisbanes/PhotoView.git 
git clone https://github.com/libgdx/libgdx.git 
git clone https://github.com/SeleniumHQ/selenium.git 
git clone https://github.com/facebook/fresco.git 
git clone https://github.com/shuzheng/zheng.git 
git clone https://github.com/Tencent/tinker.git 
git clone https://github.com/google/ExoPlayer.git 
git clone https://github.com/jenkinsci/jenkins.git 
git clone https://github.com/apache/kafka.git 
git clone https://github.com/android10/Android-CleanArchitecture.git 
git clone https://github.com/bazelbuild/bazel.git 
git clone https://github.com/lgvalle/Material-Animations.git 
git clone https://github.com/b3log/symphony.git 
git clone https://github.com/b3log/solo.git 
git clone https://github.com/DrKLO/Telegram.git 
git clone https://github.com/hdodenhof/CircleImageView.git 
git clone https://github.com/seata/seata.git 
git clone https://github.com/react-native-community/lottie-react-native.git 
git clone https://github.com/CarGuo/GSYVideoPlayer.git 
git clone https://github.com/mybatis/mybatis-3.git 
git clone https://github.com/signalapp/Signal-Android.git 
git clone https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition.git 
git clone https://github.com/openzipkin/zipkin.git 
git clone https://github.com/dianping/cat.git 
git clone https://github.com/orhanobut/logger.git 
git clone https://github.com/greenrobot/greenDAO.git 
git clone https://github.com/facebook/stetho.git 
git clone https://github.com/daimajia/AndroidSwipeLayout.git 
git clone https://github.com/JeffLi1993/springboot-learning-example.git 
git clone https://github.com/brettwooldridge/HikariCP.git 
git clone https://github.com/LMAX-Exchange/disruptor.git 
git clone https://github.com/qiurunze123/miaosha.git 
git clone https://github.com/lenve/vhr.git 
git clone https://github.com/eclipse/deeplearning4j.git 
git clone https://github.com/alibaba/canal.git 
git clone https://github.com/jfeinstein10/SlidingMenu.git 
git clone https://github.com/redisson/redisson.git 
git clone https://github.com/apache/skywalking.git 
git clone https://github.com/forezp/SpringCloudLearning.git 
git clone https://github.com/alibaba/ARouter.git 
git clone https://github.com/dbeaver/dbeaver.git 
git clone https://github.com/daimajia/AndroidViewAnimations.git 
git clone https://github.com/Curzibn/Luban.git 
git clone https://github.com/androidannotations/androidannotations.git 
git clone https://github.com/Bigkoo/Android-PickerView.git 
git clone https://github.com/wix/react-native-navigation.git 
git clone https://github.com/apache/flink.git 
git clone https://github.com/oracle/graal.git 
git clone https://github.com/xuxueli/xxl-job.git 
git clone https://github.com/alibaba/easyexcel.git 
git clone https://github.com/realm/realm-java.git 
git clone https://github.com/Konloch/bytecode-viewer.git 
git clone https://github.com/didi/DoraemonKit.git 
git clone https://github.com/android-async-http/android-async-http.git 
git clone https://github.com/eclipse-vertx/vert.x.git 
git clone https://github.com/zhihu/Matisse.git 
git clone https://github.com/Tencent/VasSonic.git 
git clone https://github.com/wuyouzhuguli/SpringAll.git 
git clone https://github.com/JakeWharton/ViewPagerIndicator.git 
git clone https://github.com/Tamsiree/RxTool.git 
git clone https://github.com/alibaba/spring-cloud-alibaba.git 
git clone https://github.com/alibaba/vlayout.git 
git clone https://github.com/linlinjava/litemall.git 
git clone https://github.com/lipangit/JiaoZiVideoPlayer.git 
git clone https://github.com/prestodb/presto.git 
git clone https://github.com/apache/hadoop.git 
git clone https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh.git 
git clone https://github.com/arduino/Arduino.git 
git clone https://github.com/wasabeef/recyclerview-animators.git 
git clone https://github.com/jeasonlzy/okhttp-OkGo.git 
git clone https://github.com/mockito/mockito.git 
git clone https://github.com/permissions-dispatcher/PermissionsDispatcher.git 
git clone https://github.com/naver/pinpoint.git 
git clone https://github.com/ksoichiro/Android-ObservableScrollView.git 
git clone https://github.com/alibaba/Sentinel.git 
git clone https://github.com/halo-dev/halo.git 
git clone https://github.com/pockethub/PocketHub.git 
git clone https://github.com/apache/rocketmq.git 
git clone https://github.com/hollischuang/toBeTopJavaer.git 
git clone https://github.com/Tencent/QMUI_Android.git 
git clone https://github.com/Yalantis/uCrop.git 
git clone https://github.com/H07000223/FlycoTabLayout.git 
git clone https://github.com/YoKeyword/Fragmentation.git 
git clone https://github.com/apache/incubator-shardingsphere.git 
git clone https://github.com/tbruyelle/RxPermissions.git 
git clone https://github.com/navasmdc/MaterialDesignLibrary.git
git clone https://github.com/github/platform-samples.git 
git clone https://github.com/alibaba/nacos.git 
git clone https://github.com/youth5201314/banner.git 
git clone https://github.com/nathanmarz/storm.git 
git clone https://github.com/iBotPeaches/Apktool.git 
git clone https://github.com/lingochamp/FileDownloader.git 
git clone https://github.com/81813780/AVLoadingIndicatorView.git 
git clone https://github.com/JessYanCoding/MVPArms.git 
git clone https://github.com/aosp-mirror/platform_frameworks_base.git 
git clone https://github.com/chrisbanes/Android-PullToRefresh.git
git clone https://github.com/apache/incubator-druid.git 
git clone https://github.com/umano/AndroidSlidingUpPanel.git 
git clone https://github.com/google/guice.git 
git clone https://github.com/xetorthio/jedis.git 
git clone https://github.com/JessYanCoding/AndroidAutoSize.git 
git clone https://github.com/google/tink.git 
git clone https://github.com/Netflix/eureka.git 
git clone https://github.com/perwendel/spark.git 
git clone https://github.com/code4craft/webmagic.git 
git clone https://github.com/rzwitserloot/lombok.git 
git clone https://github.com/material-components/material-components-android.git 
git clone https://github.com/chrisjenx/Calligraphy.git 
git clone https://github.com/Netflix/zuul.git 
git clone https://github.com/android-hacker/VirtualXposed.git 
git clone https://github.com/roughike/BottomBar.git 
git clone https://github.com/looly/hutool.git 
git clone https://github.com/wasabeef/glide-transformations.git 
git clone https://github.com/pagehelper/Mybatis-PageHelper.git 
git clone https://github.com/google/auto.git 
git clone https://github.com/bilibili/DanmakuFlameMaster.git 
git clone https://github.com/medcl/elasticsearch-analysis-ik.git 
git clone https://github.com/Freelander/Android_Data.git 
git clone https://github.com/florent37/MaterialViewPager.git 
git clone https://github.com/clojure/clojure.git 
git clone https://github.com/googlesamples/easypermissions.git 
git clone https://github.com/codecentric/spring-boot-admin.git 
git clone https://github.com/react-native-community/react-native-camera.git 
git clone https://github.com/koral--/android-gif-drawable.git 
git clone https://github.com/HannahMitt/HomeMirror.git 
git clone https://github.com/laobie/StatusBarUtil.git 
git clone https://github.com/GoogleContainerTools/jib.git 
git clone https://github.com/chrisbanes/cheesesquare.git 
git clone https://github.com/junit-team/junit4.git 
git clone https://github.com/didi/VirtualAPK.git 
git clone https://github.com/daniulive/SmarterStreaming.git 
git clone https://github.com/java-decompiler/jd-gui.git 
git clone https://github.com/jhy/jsoup.git 
git clone https://github.com/sqshq/piggymetrics.git 
git clone https://github.com/GcsSloop/AndroidNote.git 
git clone https://github.com/square/javapoet.git 
git clone https://github.com/dropwizard/dropwizard.git 
git clone https://github.com/LuckSiege/PictureSelector.git 
git clone https://github.com/ChrisRM/material-theme-jetbrains.git 
git clone https://github.com/alibaba/atlas.git 
git clone https://github.com/Netflix/SimianArmy.git 
git clone https://github.com/google/agera.git 
git clone https://github.com/gyf-dev/ImmersionBar.git 
git clone https://github.com/apache/zookeeper.git 
git clone https://github.com/JakeWharton/ActionBarSherlock.git 
git clone https://github.com/MyCATApache/Mycat-Server.git 
git clone https://github.com/lzyzsd/JsBridge.git 
git clone https://github.com/trello/RxLifecycle.git 
git clone https://github.com/kaushikgopal/RxJava-Android-Samples.git 
git clone https://github.com/square/dagger.git 
git clone https://github.com/cymcsg/UltimateRecyclerView.git 
git clone https://github.com/lionsoul2014/ip2region.git 
git clone https://github.com/janishar/mit-deep-learning-book-pdf.git 
git clone https://github.com/JakeWharton/hugo.git 
git clone https://github.com/Bearded-Hen/Android-Bootstrap.git 
git clone https://github.com/hackware1993/MagicIndicator.git 
git clone https://github.com/neo4j/neo4j.git 
git clone https://github.com/facebook/buck.git 
git clone https://github.com/zhangdaiscott/jeecg-boot.git 
git clone https://github.com/baomidou/mybatis-plus.git 
git clone https://github.com/xkcoding/spring-boot-demo.git 
git clone https://github.com/frank-lam/fullstack-tutorial.git 
git clone https://github.com/aritraroy/UltimateAndroidReference.git 
git clone https://github.com/TeamNewPipe/NewPipe.git 
git clone https://github.com/android/testing-samples.git 
git clone https://github.com/geeeeeeeeek/WeChatLuckyMoney.git 
git clone https://github.com/hs-web/hsweb-framework.git 
git clone https://github.com/pxb1988/dex2jar.git 
git clone https://github.com/apereo/cas.git 
git clone https://github.com/grpc/grpc-java.git 
git clone https://github.com/pedant/sweet-alert-dialog.git 
git clone https://github.com/dropwizard/metrics.git 
git clone https://github.com/lecho/hellocharts-android.git 
git clone https://github.com/hongyangAndroid/okhttputils.git 
git clone https://github.com/ben-manes/caffeine.git 
git clone https://github.com/Blankj/awesome-java-leetcode.git 
git clone https://github.com/LitePalFramework/LitePal.git 
git clone https://github.com/ybq/Android-SpinKit.git 
git clone https://github.com/hongyangAndroid/AndroidAutoLayout.git 
git clone https://github.com/stanfordnlp/CoreNLP.git 
git clone https://github.com/crazycodeboy/TakePhoto.git 
git clone https://github.com/OpenRefine/OpenRefine.git 
git clone https://github.com/antlr/antlr4.git 
git clone https://github.com/amitshekhariitbhu/Android-Debug-Database.git 
git clone https://github.com/zaproxy/zaproxy.git 
git clone https://github.com/cats-oss/android-gpuimage.git 
git clone https://github.com/Justson/AgentWeb.git 
git clone https://github.com/koush/AndroidAsync.git 
git clone https://github.com/ogaclejapan/SmartTabLayout.git 
git clone https://github.com/facebook/litho.git 
git clone https://github.com/paascloud/paascloud-master.git 
git clone https://github.com/leolin310148/ShortcutBadger.git 
git clone https://github.com/asLody/VirtualApp.git 
git clone https://github.com/shwenzhang/AndResGuard.git 
git clone https://github.com/firebase/quickstart-android.git 
git clone https://github.com/DroidPluginTeam/DroidPlugin.git 
git clone https://github.com/vipshop/vjtools.git 
git clone https://github.com/futuresimple/android-floating-action-button.git 
git clone https://github.com/google/physical-web.git 
git clone https://github.com/TooTallNate/Java-WebSocket.git 
git clone https://github.com/swagger-api/swagger-core.git 
git clone https://github.com/koush/ion.git 
git clone https://github.com/Qihoo360/RePlugin.git 
git clone https://github.com/pedrovgs/EffectiveAndroidUI.git 
git clone https://github.com/naman14/Timber.git 
git clone https://github.com/airbnb/epoxy.git 
git clone https://github.com/Activiti/Activiti.git 
git clone https://github.com/ikew0ng/SwipeBackLayout.git 
git clone https://github.com/google/android-classyshark.git 
git clone https://github.com/rey5137/material.git 
git clone https://github.com/apache/storm.git 
git clone https://github.com/yanzhenjie/AndPermission.git 
git clone https://github.com/rengwuxian/MaterialEditText.git 
git clone https://github.com/antoniolg/androidmvp.git 
git clone https://github.com/react-native-community/react-native-image-picker.git 
git clone https://github.com/seaswalker/spring-analysis.git 
git clone https://github.com/eclipse/che.git 
git clone https://github.com/huanghaibin-dev/CalendarView.git 
git clone https://github.com/singwhatiwanna/dynamic-load-apk.git 
git clone https://github.com/springside/springside4.git 
git clone https://github.com/vinc3m1/RoundedImageView.git 
git clone https://github.com/davemorrissey/subsampling-scale-image-view.git 
git clone https://github.com/nhaarman/ListViewAnimations.git 
git clone https://github.com/JakeWharton/u2020.git 
git clone https://github.com/daimajia/NumberProgressBar.git
git clone https://github.com/square/moshi.git 
git clone https://github.com/wyouflf/xUtils3.git 
git clone https://github.com/jwtk/jjwt.git 
git clone https://github.com/GrenderG/Toasty.git 
git clone https://github.com/google/j2objc.git 
git clone https://github.com/NLPchina/elasticsearch-sql.git 
git clone https://github.com/careercup/CtCI-6th-Edition.git 
git clone https://github.com/apache/cassandra.git 
git clone https://github.com/amlcurran/ShowcaseView.git 
git clone https://github.com/daimajia/AndroidImageSlider.git 
git clone https://github.com/lihengming/spring-boot-api-project-seed.git 
git clone https://github.com/emilsjolander/StickyListHeaders.git
git clone https://github.com/Nightonke/BoomMenu.git 
git clone https://github.com/Devlight/InfiniteCycleViewPager.git 
git clone https://github.com/aa112901/remusic.git 
git clone https://github.com/facebook/rebound.git 
git clone https://github.com/elasticjob/elastic-job-lite.git 
git clone https://github.com/evant/gradle-retrolambda.git 
git clone https://github.com/smuyyh/BookReader.git 
git clone https://github.com/MindorksOpenSource/android-interview-questions.git 
git clone https://github.com/Angel-ML/angel.git 
git clone https://github.com/dmytrodanylyk/circular-progress-button.git 
git clone https://github.com/markzhai/AndroidPerformanceMonitor.git 
git clone https://github.com/evernote/android-job.git 
git clone https://github.com/sockeqwe/mosby.git 
git clone https://github.com/lucasr/twoway-view.git 
git clone https://github.com/kickstarter/android-oss.git 
git clone https://github.com/sparklemotion/nokogiri.git 
git clone https://github.com/java-native-access/jna.git 
git clone https://github.com/weibocom/motan.git 
git clone https://github.com/prolificinteractive/material-calendarview.git 
git clone https://github.com/hongyangAndroid/FlowLayout.git 
git clone https://github.com/gocd/gocd.git 
git clone https://github.com/alibaba/otter.git 
git clone https://github.com/justauth/JustAuth.git 
git clone https://github.com/square/otto.git 
git clone https://github.com/NLPchina/ansj_seg.git 
git clone https://github.com/barteksc/AndroidPdfViewer.git 
git clone https://github.com/alibaba/freeline.git 
git clone https://github.com/google/closure-compiler.git
git clone https://github.com/JakeWharton/DiskLruCache.git 
git clone https://github.com/AsyncHttpClient/async-http-client.git 
git clone https://github.com/kevin-wayne/algs4.git 
git clone https://github.com/processing/processing.git 
git clone https://github.com/uber/RIBs.git 
git clone https://github.com/DuGuQiuBai/Java.git 
git clone https://github.com/ACRA/acra.git 
git clone https://github.com/NanoHttpd/nanohttpd.git 
git clone https://github.com/OpenFeign/feign.git 
git clone https://github.com/Graylog2/graylog2-server.git 
git clone https://github.com/XRecyclerView/XRecyclerView.git 
git clone https://github.com/commonsguy/cw-omnibus.git 
git clone https://github.com/izzyleung/ZhihuDailyPurify.git 
git clone https://github.com/lets-blade/blade.git 
git clone https://github.com/frogermcs/InstaMaterial.git 
git clone https://github.com/thinkaurelius/titan.git 
git clone https://github.com/facebook/facebook-android-sdk.git 
git clone https://github.com/dyc87112/SpringCloud-Learning.git 
git clone https://github.com/Meituan-Dianping/walle.git 
git clone https://github.com/Yalantis/Side-Menu.Android.git 
git clone https://github.com/scribejava/scribejava.git 
git clone https://github.com/dm77/barcodescanner.git 
git clone https://github.com/Clans/FloatingActionButton.git 
git clone https://github.com/Trinea/android-common.git 
git clone https://github.com/google/error-prone.git 
git clone https://github.com/checkstyle/checkstyle.git 
git clone https://github.com/traex/RippleEffect.git 
git clone https://github.com/motianhuo/wechat.git 
git clone https://github.com/ArthurHub/Android-Image-Cropper.git 
git clone https://github.com/jpush/aurora-imui.git 
git clone https://github.com/guardianproject/haven.git 
git clone https://github.com/claritylab/lucida.git 
git clone https://github.com/yarolegovich/DiscreteScrollView.git 
git clone https://github.com/elunez/eladmin.git 
git clone https://github.com/gzu-liyujiang/AndroidPicker.git 
git clone https://github.com/wasabeef/richeditor-android.git 
git clone https://github.com/wequick/Small.git 
git clone https://github.com/zetbaitsu/Compressor.git 
git clone https://github.com/gabrielemariotti/cardslib.git 
git clone https://github.com/etsy/AndroidStaggeredGrid.git 
git clone https://github.com/hanks-zyh/HTextView.git 
git clone https://github.com/joelittlejohn/jsonschema2pojo.git 
git clone https://github.com/abel533/Mapper.git 
git clone https://github.com/robolectric/robolectric.git 
git clone https://github.com/alibaba/UltraViewPager.git 
git clone https://github.com/square/sqlbrite.git 
git clone https://github.com/h6ah4i/android-advancedrecyclerview.git 
git clone https://github.com/pardom-zz/ActiveAndroid.git 
git clone https://github.com/keycloak/keycloak.git 
git clone https://github.com/zouzg/mybatis-generator-gui.git 
git clone https://github.com/Devlight/NavigationTabBar.git 
git clone https://github.com/spring-projects/spring-mvc-showcase.git 
git clone https://github.com/careercup/ctci.git 
git clone https://github.com/real-logic/aeron.git
git clone https://github.com/k0shk0sh/FastHub.git 
git clone https://github.com/KeepSafe/TapTargetView.git 
git clone https://github.com/orhanobut/dialogplus.git 
git clone https://github.com/liyifeng1994/ssm.git 
git clone https://github.com/amitshekhariitbhu/Fast-Android-Networking.git 
git clone https://github.com/amitshekhariitbhu/RxJava2-Android-Samples.git 
git clone https://github.com/termux/termux-app.git 
git clone https://github.com/andkulikov/Transitions-Everywhere.git 
git clone https://github.com/k9mail/k-9.git 
git clone https://github.com/google/cameraview.git 
git clone https://github.com/lightbend/config.git 
git clone https://github.com/flyway/flyway.git 
git clone https://github.com/chentao0707/SimplifyReader.git 
git clone https://github.com/sohutv/cachecloud.git 
git clone https://github.com/TechEmpower/FrameworkBenchmarks.git 
git clone https://github.com/go-lang-plugin-org/go-lang-idea-plugin.git 
git clone https://github.com/Ramotion/folding-cell-android.git 
git clone https://github.com/ityouknow/spring-cloud-examples.git 
git clone https://github.com/haifengl/smile.git 
git clone https://github.com/saiwu-bigkoo/Android-ConvenientBanner.git 
git clone https://github.com/danielzeller/Depth-LIB-Android-.git 
git clone https://github.com/JakeWharton/NineOldAndroids.git 
git clone https://github.com/seven332/EhViewer.git 
git clone https://github.com/thingsboard/thingsboard.git 
git clone https://github.com/react-native-community/react-native-video.git 
git clone https://github.com/resilience4j/resilience4j.git 
git clone https://github.com/Vedenin/useful-java-links.git 
git clone https://github.com/wuhaoyu1990/MagicCamera.git&
git clone https://github.com/CameraKit/camerakit-android.git 
git clone https://github.com/hongyangAndroid/baseAdapter.git 
git clone https://github.com/h2oai/h2o-3.git 
git clone https://github.com/yipianfengye/android-zxingLibrary.git 
git clone https://github.com/mcxiaoke/android-volley.git 
git clone https://github.com/apache/zeppelin.git 
git clone https://github.com/jdamcd/android-crop.git 
git clone https://github.com/apache/pulsar.git 
git clone https://github.com/MindorksOpenSource/from-java-to-kotlin.git 
git clone https://github.com/square/android-times-square.git 
git clone https://github.com/Alluxio/alluxio.git 
git clone https://github.com/rubensousa/GravitySnapHelper.git 
git clone https://github.com/yanzhenjie/SwipeRecyclerView.git 
git clone https://github.com/zo0r/react-native-push-notification.git 
git clone https://github.com/react-native-community/react-native-device-info.git 
git clone https://github.com/mcxiaoke/packer-ng-plugin.git 
git clone https://github.com/ximsfei/Android-skin-support.git 
git clone https://github.com/mrniko/netty-socketio.git 
git clone https://github.com/hyb1996/Auto.js.git 
git clone https://github.com/Flipboard/bottomsheet.git 
git clone https://github.com/rabbitmq/rabbitmq-tutorials.git 
git clone https://github.com/jfoenixadmin/JFoenix.git 
git clone https://github.com/json-path/JsonPath.git 
git clone https://github.com/Exrick/xmall.git 
git clone https://github.com/zhanghai/Douya.git 
git clone https://github.com/rest-assured/rest-assured.git 
git clone https://github.com/aporter/coursera-android.git 
git clone https://github.com/castorflex/SmoothProgressBar.git 
git clone https://github.com/TommyLemon/Android-ZBLibrary.git 
git clone https://github.com/JetBrains/ideavim.git 
git clone https://github.com/AndroidBootstrap/android-bootstrap.git 
git clone https://github.com/goldze/MVVMHabit.git 
git clone https://github.com/wasabeef/Blurry.git 
git clone https://github.com/JodaOrg/joda-time.git 
git clone https://github.com/wdullaer/MaterialDateTimePicker.git 
git clone https://github.com/wildfirechat/server.git 
git clone https://github.com/changmingxie/tcc-transaction.git 
git clone https://github.com/crossoverJie/cim.git
git clone https://github.com/alibaba/dexposed.git 
git clone https://github.com/kyleduo/SwitchButton.git 
git clone https://github.com/SonarSource/sonarqube.git 
git clone https://github.com/Karumi/Dexter.git 
git clone https://github.com/google/grafika.git 
git clone https://github.com/react-native-community/react-native-svg.git &
git clone https://github.com/hibernate/hibernate-orm.git 
git clone https://github.com/SplashCodes/JAViewer.git 
git clone https://github.com/makovkastar/FloatingActionButton.git 
git clone https://github.com/bingoogolapple/BGARefreshLayout-Android.git 
git clone https://github.com/romandanylyk/PageIndicatorView.git 
git clone https://github.com/pili-engineering/PLDroidPlayer.git 
git clone https://github.com/pedrovgs/AndroidWiFiADB.git 
git clone https://github.com/alibaba/DataX.git 
git clone https://github.com/nisrulz/android-tips-tricks.git 
git clone https://github.com/jgilfelt/chuck.git 
git clone https://github.com/MindorksOpenSource/android-mvp-architecture.git 
git clone https://github.com/apache/dubbo-spring-boot-project.git 
git clone https://github.com/spring-projects/spring-security.git 
git clone https://github.com/orientechnologies/orientdb.git 
git clone https://github.com/Ashok-Varma/BottomNavigation.git 
git clone https://github.com/Yalantis/Phoenix.git 
git clone https://github.com/springfox/springfox.git 
git clone https://github.com/socketio/socket.io-client-java.git 
git clone https://github.com/youlookwhat/CloudReader.git 
git clone https://github.com/JesusFreke/smali.git 
git clone https://github.com/dengyuhan/magnetW.git 
git clone https://github.com/grantland/android-autofittextview.git
git clone https://github.com/mybatis/generator.git 
git clone https://github.com/mybatis/generator.git 
git clone https://github.com/DingMouRen/LayoutManagerGroup.git
git clone https://github.com/apache/tomcat.git 
git clone https://github.com/jeasonlzy/ImagePicker.git 
git clone https://github.com/journeyapps/zxing-android-embedded.git 
git clone https://github.com/OpenTSDB/opentsdb.git 
git clone https://github.com/rengwuxian/RxJavaSamples.git 
git clone https://github.com/alibaba/jstorm.git 
git clone https://github.com/Tencent/GT.git 
git clone https://github.com/hugeterry/CoordinatorTabLayout.git 
git clone https://github.com/baoyachi/StepView.git 
git clone https://github.com/JoanZapata/android-iconify.git 
git clone https://github.com/spring-projects/spring-security-oauth.git 
git clone https://github.com/gedoor/MyBookshelf.git 
git clone https://github.com/roboguice/roboguice.git 
git clone https://github.com/google/google-authenticator.git 
git clone https://github.com/rubensousa/ViewPagerCards.git 
git clone https://github.com/jankotek/mapdb.git 
git clone https://github.com/dinuscxj/LoadingDrawable.git 
git clone https://github.com/graphql-java/graphql-java.git 
git clone https://github.com/ChadCSong/ShineButton.git 
git clone https://github.com/BoltsFramework/Bolts-Android.git 
git clone https://github.com/bytedeco/javacv.git 
git clone https://github.com/puniverse/quasar.git 
git clone https://github.com/crazycodeboy/react-native-splash-screen.git 
git clone https://github.com/danikula/AndroidVideoCache.git 
git clone https://github.com/spring-cloud/spring-cloud-netflix.git 
git clone https://github.com/Jacksgong/JKeyboardPanelSwitch.git 
git clone https://github.com/aurelhubert/ahbottomnavigation.git 
git clone https://github.com/huangyanbin/smartTable.git 
git clone https://github.com/yasserg/crawler4j.git 
git clone https://github.com/robinhood/ticker.git 
git clone https://github.com/lcodecorex/TwinklingRefreshLayout.git 
git clone https://github.com/facebook/shimmer-android.git 
git clone https://github.com/yanzhenjie/NoHttp.git 
git clone https://github.com/awangdev/LintCode.git
git clone https://github.com/wuyouzhuguli/FEBS-Shiro.git 
git clone https://github.com/bingoogolapple/BGABanner-Android.git 
git clone https://github.com/Tencent/Shadow.git 
git clone https://github.com/spring-projects/spring-petclinic.git 
git clone https://github.com/firebase/FirebaseUI-Android.git 
git clone https://github.com/ZXZxin/ZXBlog.git 
git clone https://github.com/MiguelCatalan/MaterialSearchView.git 
git clone https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector.git 
git clone https://github.com/timehop/sticky-headers-recyclerview.git 
git clone https://github.com/OpenAPITools/openapi-generator.git 
git clone https://github.com/Manabu-GT/ExpandableTextView.git 
git clone https://github.com/nytimes/Store.git 
git clone https://github.com/bluelinelabs/Conductor.git
git clone https://github.com/airbnb/DeepLinkDispatch.git 
git clone https://github.com/qstumn/BadgeView.git 
git clone https://github.com/xcltapestry/XCL-Charts.git 
git clone https://github.com/apache/jmeter.git 
git clone https://github.com/rockerhieu/emojicon.git 
git clone https://github.com/johncarl81/parceler.git 
git clone https://github.com/gephi/gephi.git 
git clone https://github.com/junit-team/junit5.git 
git clone https://github.com/amirzaidi/Launcher3.git 
git clone https://github.com/tomakehurst/wiremock.git
git clone https://github.com/orhanobut/hawk.git 
git clone https://github.com/ongakuer/CircleIndicator.git 
git clone https://github.com/ffay/lanproxy.git 
git clone https://github.com/luontola/retrolambda.git 
git clone https://github.com/vavr-io/vavr.git 
git clone https://github.com/li-xiaojun/XPopup.git 
git clone https://github.com/baoyongzhang/SwipeMenuListView.git 
git clone https://github.com/openhab/openhab1-addons.git 
git clone https://github.com/lsjwzh/RecyclerViewPager.git 
git clone https://github.com/bitcoinj/bitcoinj.git 
git clone https://github.com/razerdp/BasePopup.git 
git clone https://github.com/apache/beam.git 
git clone https://github.com/litesuits/android-common.git 
git clone https://github.com/tyrantgit/ExplosionField.git 
git clone https://github.com/apache/groovy.git 
git clone https://github.com/cjlin1/libsvm.git 
git clone https://github.com/yangfuhai/ASimpleCache.git 
git clone https://github.com/xcc3641/SeeWeather.git 
git clone https://github.com/codeestX/GeekNews.git 
git clone https://github.com/avast/android-butterknife-zelezny.git 
git clone https://github.com/ryanhoo/StylishMusicPlayer.git 
git clone https://github.com/lzyzsd/CircleProgress.git 
git clone https://github.com/cryptomator/cryptomator.git 
git clone https://github.com/apache/incubator-heron.git 
git clone https://github.com/MinecraftForge/MinecraftForge.git 
git clone https://github.com/hazelcast/hazelcast.git 
git clone https://github.com/stleary/JSON-java.git 
git clone https://github.com/Meituan-Dianping/Robust.git 
git clone https://github.com/btraceio/btrace.git 
git clone https://github.com/microsoft/malmo.git
git clone https://github.com/dongjunkun/DropDownMenu.git 
git clone https://github.com/siacs/Conversations.git 
git clone https://github.com/kikoso/android-stackblur.git 
git clone https://github.com/Atmosphere/atmosphere.git 
git clone https://github.com/sofastack/sofa-boot.git 
git clone https://github.com/yigit/android-priority-jobqueue.git 
git clone https://github.com/Jasonchenlijian/FastBle.git 
git clone https://github.com/reactive-streams/reactive-streams-jvm.git 
git clone https://github.com/Piasy/BigImageViewer.git 
git clone https://github.com/pentaho/pentaho-kettle.git 
git clone https://github.com/ivacf/archi.git 
git clone https://github.com/objectbox/objectbox-java.git 
git clone https://github.com/dropbox/hackpad.git 
git clone https://github.com/arimorty/floatingsearchview.git 
git clone https://github.com/Freeyourgadget/Gadgetbridge.git 
git clone https://github.com/bilibili/MagicaSakura.git 
git clone https://github.com/actorapp/actor-platform.git 
git clone https://github.com/willowtreeapps/spruce-android.git 
git clone https://github.com/andremion/Music-Player.git 
git clone https://github.com/alibaba/Tangram-Android.git 
git clone https://github.com/chrisbanes/ActionBar-PullToRefresh.git 
git clone https://github.com/Netflix/ribbon.git 
git clone https://github.com/davideas/FlexibleAdapter.git 
git clone https://github.com/tangqi92/Android-Tips.git 
git clone https://github.com/bluelinelabs/LoganSquare.git 
git clone https://github.com/apache/hbase.git 
git clone https://github.com/sharish/ShimmerRecyclerView.git 
git clone https://github.com/quartz-scheduler/quartz.git 
git clone https://github.com/bauerca/drag-sort-listview.git 
git clone https://github.com/databricks/learning-spark.git 
git clone https://github.com/yangfuhai/afinal.git 
git clone https://github.com/brianway/java-learning.git 
git clone https://github.com/hustcc/JS-Sorting-Algorithm.git 
git clone https://github.com/sunfusheng/MarqueeView.git 
git clone https://github.com/techGay/v9porn.git 
git clone https://github.com/pengjianbo/GalleryFinal.git 
git clone https://github.com/alamkanak/Android-Week-View.git 
git clone https://github.com/languagetool-org/languagetool.git 
git clone https://github.com/shekhargulati/99-problems.git 
git clone https://github.com/auth0/java-jwt.git 
git clone https://github.com/oldmanpushcart/greys-anatomy.git 
git clone https://github.com/zzhoujay/RichText.git 
git clone https://github.com/luckybilly/CC.git 
git clone https://github.com/cglib/cglib.git 
git clone https://github.com/daimajia/AndroidViewHover.git 
git clone https://github.com/raphw/byte-buddy.git 
git clone https://github.com/airbnb/native-navigation.git 
git clone https://github.com/spring-projects/spring-data-examples.git 
git clone https://github.com/yhaolpz/FloatWindow.git 
git clone https://github.com/hitherejoe/animate.git 
git clone https://github.com/oblac/jodd.git 
git clone https://github.com/lingochamp/okdownload.git 
git clone https://github.com/testcontainers/testcontainers-java.git 
git clone https://github.com/alibaba/jvm-sandbox.git 
git clone https://github.com/ming1016/study.git 
git clone https://github.com/hope-for/hope-boot.git 
git clone https://github.com/aws/aws-sdk-java.git 
git clone https://github.com/ragunathjawahar/android-saripaar.git 
git clone https://github.com/bilibili/boxing.git 
git clone https://github.com/binIoter/GuideView.git 
git clone https://github.com/lygttpod/SuperTextView.git 
git clone https://github.com/keyboardsurfer/Crouton.git 
git clone https://github.com/pqpo/SmartCropper.git 
git clone https://github.com/roncoo/roncoo-pay.git 
git clone https://github.com/JakeWharton/ThreeTenABP.git 
git clone https://github.com/gabrielemariotti/RecyclerViewItemAnimators.git 
git clone https://github.com/nicolasgramlich/AndEngine.git 
git clone https://github.com/iammert/ScalingLayout.git 
git clone https://github.com/sherxon/AlgoDS.git 
git clone https://github.com/jgilfelt/android-viewbadger.git 
git clone https://github.com/phishman3579/java-algorithms-implementation.git 
git clone https://github.com/apache/lucene-solr.git 
git clone https://github.com/eirslett/frontend-maven-plugin.git 
git clone https://github.com/crossoverJie/SSM.git 
git clone https://github.com/LawnchairLauncher/Lawnchair.git 
git clone https://github.com/deathmarine/Luyten.git 
git clone https://github.com/CameraKit/blurkit-android.git 
git clone https://github.com/stephanenicolas/robospice.git 
git clone https://github.com/guolindev/giffun.git 
git clone https://github.com/codingapi/tx-lcn.git 
git clone https://github.com/jhalterman/failsafe.git 
git clone https://github.com/macrozheng/mall-learning.git 
git clone https://github.com/micronaut-projects/micronaut-core.git 
git clone https://github.com/527515025/springBoot.git 
git clone https://github.com/CalebFenton/simplify.git 
git clone https://github.com/rubensousa/PreviewSeekBar.git
git clone https://github.com/udacity/Sunshine-Version-2.git 
git clone https://github.com/zwwill/yanxuan-weex-demo.git 
git clone https://github.com/kevinsawicki/http-request.git 
git clone https://github.com/facebook/network-connection-class.git 
git clone https://github.com/Skykai521/StickerCamera.git 
git clone https://github.com/luojilab/DDComponentForAndroid.git 
git clone https://github.com/quarkusio/quarkus.git 
git clone https://github.com/zzz40500/GsonFormat.git 
git clone https://github.com/vespa-engine/vespa.git 
git clone https://github.com/mcxtzhang/SwipeDelMenuLayout.git 
git clone https://github.com/bin456789/Unblock163MusicClient-Xposed.git 
git clone https://github.com/ThirtyDegreesRay/OpenHub.git 
git clone https://github.com/amulyakhare/TextDrawable.git 
git clone https://github.com/jfinal/jfinal.git 
git clone https://github.com/pedrovgs/DraggablePanel.git 
git clone https://github.com/square/wire.git 
git clone https://github.com/psaravan/JamsMusicPlayer.git 
git clone https://github.com/yipianfengye/android-adDialog.git 
git clone https://github.com/rstudio/rstudio.git 
git clone https://github.com/lovetuzitong/MultiImageSelector.git 
git clone https://github.com/GitLqr/LQRWeChat.git
git clone https://github.com/sofastack/sofa-jarslink.git 
git clone https://github.com/stfalcon-studio/ChatKit.git 
git clone https://github.com/apache/camel.git 
git clone https://github.com/bytedeco/javacpp.git 
git clone https://github.com/dmytrodanylyk/android-process-button.git 
git clone https://github.com/bisq-network/bisq.git 
git clone https://github.com/ManuelPeinado/FadingActionBar.git 
git clone https://github.com/google/google-java-format.git 
git clone https://github.com/alibaba/flutter_boost.git 
git clone https://github.com/HoraApps/LeafPic.git 
git clone https://github.com/race604/FlyRefresh.git 
git clone https://github.com/Ereza/CustomActivityOnCrash.git 
git clone https://github.com/saulmm/Android-Material-Examples.git 
git clone https://github.com/hmkcode/Android.git 
git clone https://github.com/jasonross/Nuwa.git 
git clone https://github.com/hongyangAndroid/Highlight.git 
git clone https://github.com/jersey/jersey.git 
git clone https://github.com/alipay/SoloPi.git 
git clone https://github.com/sofastack/sofa-rpc.git 
git clone https://github.com/googlemaps/android-maps-utils.git 
git clone https://github.com/YahooArchive/anthelion.git 
git clone https://github.com/dreamhead/moco.git 
git clone https://github.com/azkaban/azkaban.git 
git clone https://github.com/requery/requery.git 
git clone https://github.com/google/open-location-code.git 
git clone https://github.com/chewiebug/GCViewer.git 
git clone https://github.com/danylovolokh/VideoPlayerManager.git 
git clone https://github.com/abel533/MyBatis-Spring-Boot.git 
git clone https://github.com/zhanglei-workspace/shopping-management-system.git 
git clone https://github.com/lettuce-io/lettuce-core.git 
git clone https://github.com/xmuSistone/ViewpagerTransition.git 
git clone https://github.com/owncloud/android.git 
git clone https://github.com/ronmamo/reflections.git 
git clone https://github.com/youtube/api-samples.git 
git clone https://github.com/JanusGraph/janusgraph.git 
git clone https://github.com/eishay/jvm-serializers.git 
git clone https://github.com/apache/hive.git 
git clone https://github.com/mpusher/mpush.git 
git clone https://github.com/donglua/PhotoPicker.git 
git clone https://github.com/AriaLyy/Aria.git
git clone https://github.com/knowm/XChange.git 
git clone https://github.com/apache/ignite.git 
git clone https://github.com/JulienGenoud/android-percent-support-lib-sample.git 
git clone https://github.com/yui/yuicompressor.git 
git clone https://github.com/powermock/powermock.git 
git clone https://github.com/SpecialCyCi/AndroidResideMenu.git 
git clone https://github.com/Marswin/MarsDaemon.git 
git clone https://github.com/rovo89/XposedInstaller.git 
git clone https://github.com/edmodo/cropper.git 
git clone https://github.com/openaphid/android-flip.git 
git clone https://github.com/apache/cordova-android.git 
git clone https://github.com/alibaba/cobar.git 
git clone https://github.com/jiangqqlmj/FastDev4Android.git 
git clone https://github.com/ittianyu/BottomNavigationViewEx.git 
git clone https://github.com/BelooS/ChipsLayoutManager.git 
git clone https://github.com/WVector/AppUpdate.git 
git clone https://github.com/square/flow.git
git clone https://github.com/hussien89aa/AndroidTutorialForBeginners.git 
git clone https://github.com/JZ-Darkal/AndroidHttpCapture.git 
git clone https://github.com/brianfrankcooper/YCSB.git 
git clone https://github.com/Exrick/xpay.git
git clone https://github.com/mercyblitz/tech-weekly.git 
git clone https://github.com/javaparser/javaparser.git 
git clone https://github.com/iSoron/uhabits.git 
git clone https://github.com/w446108264/XhsEmoticonsKeyboard.git 
git clone https://github.com/chenBingX/SuperTextView.git 
git clone https://github.com/sunfusheng/StickyHeaderListView.git 
git clone https://github.com/geftimov/android-pathview.git 
git clone https://github.com/mzule/ActivityRouter.git 
git clone https://github.com/mybatis/spring-boot-starter.git 
git clone https://github.com/jprante/elasticsearch-jdbc.git
git clone https://github.com/google/data-transfer-project.git 
git clone https://github.com/fyhertz/libstreaming.git
git clone https://github.com/code-troopers/android-betterpickers.git 
git clone https://github.com/apache/incubator-dolphinscheduler.git 
git clone https://github.com/JakeWharton/scalpel.git 
git clone https://github.com/north2016/T-MVP.git 
git clone https://github.com/oracle/opengrok.git 
git clone https://github.com/eleme/UETool.git 
git clone https://github.com/code4craft/netty-learning.git 
git clone https://github.com/apache/shiro.git 
git clone https://github.com/florent37/ExpectAnim.git 
git clone https://github.com/jenkinsci/blueocean-plugin.git 
git clone https://github.com/glomadrian/Grav.git 
git clone https://github.com/zaaach/CityPicker.git 
git clone https://github.com/web3j/web3j.git 
git clone https://github.com/google/binnavi.git 
git clone https://github.com/crazyandcoder/citypicker.git 
git clone https://github.com/mihaip/dex-method-counts.git 
git clone https://github.com/pedrovgs/Algorithms.git 
git clone https://github.com/coobird/thumbnailator.git 
git clone https://github.com/guoguibing/librec.git 
git clone https://github.com/Nightonke/WoWoViewPager.git 
git clone https://github.com/MovingBlocks/Terasology.git 
git clone https://github.com/reactor/reactor-core.git 
git clone https://github.com/SimonVT/android-menudrawer.git 
git clone https://github.com/JoanZapata/android-pdfview.git 
git clone https://github.com/nanchen2251/RxJava2Examples.git 
git clone https://github.com/WritingMinds/ffmpeg-android-java.git 
git clone https://github.com/linkedin/databus.git 
git clone https://github.com/bmelnychuk/AndroidTreeView.git 
git clone https://github.com/liangfeidotme/MasteringAndroidDataBinding.git 
git clone https://github.com/Malinskiy/SuperRecyclerView.git 
git clone https://github.com/yarolegovich/SlidingRootNav.git 
git clone https://github.com/JohnPersano/SuperToasts.git 
git clone https://github.com/zhisheng17/flink-learning.git 
git clone https://github.com/uber/NullAway.git 
git clone https://github.com/pushtorefresh/storio.git 
git clone https://github.com/woxingxiao/BubbleSeekBar.git 
git clone https://github.com/google/rejoiner.git 
git clone https://github.com/Teevity/ice.git 
git clone https://github.com/uber/AutoDispose.git 
git clone https://github.com/saulmm/CoordinatorBehaviorExample.git 
git clone https://github.com/beworker/pinned-section-listview.git 
git clone https://github.com/confluentinc/ksql.git 
git clone https://github.com/moezbhatti/qksms.git 
git clone https://github.com/chennaione/sugar.git 
git clone https://github.com/iwgang/CountdownView.git 
git clone https://github.com/cyrilmottier/GreenDroid.git 
git clone https://github.com/oguzbilgener/CircularFloatingActionMenu.git 
git clone https://github.com/linyiqun/DataMiningAlgorithm.git 
git clone https://github.com/MagicMashRoom/SuperCalendar.git 
git clone https://github.com/Todd-Davies/ProgressWheel.git 
git clone https://github.com/crate/crate.git 
git clone https://github.com/lizhangqu/CoreLink.git 
git clone https://github.com/RobotiumTech/robotium.git 
git clone https://github.com/bigbluebutton/bigbluebutton.git 
git clone https://github.com/airbnb/airpal.git 
git clone https://github.com/facebook/react-native-fbsdk.git 
git clone https://github.com/wenmingvs/AndroidProcess.git 
git clone https://github.com/TangoAgency/material-intro-screen.git 
git clone https://github.com/frohoff/ysoserial.git 
git clone https://github.com/Dromara/hmily.git 
git clone https://github.com/zhou-you/RxEasyHttp.git 
git clone https://github.com/JackyAndroid/AndroidChromium.git 
git clone https://github.com/jenkinsci/blueocean-plugin.git 
git clone https://github.com/glomadrian/Grav.git 
git clone https://github.com/zaaach/CityPicker.git 
git clone https://github.com/web3j/web3j.git 
git clone https://github.com/google/binnavi.git 
git clone https://github.com/crazyandcoder/citypicker.git 
git clone https://github.com/mihaip/dex-method-counts.git 
git clone https://github.com/pedrovgs/Algorithms.git 
git clone https://github.com/coobird/thumbnailator.git 
git clone https://github.com/guoguibing/librec.git 
git clone https://github.com/googlearchive/android-ConstraintLayoutExamples.git 
git clone https://github.com/Nightonke/CoCoin.git 
git clone https://github.com/kiegroup/drools.git 
git clone https://github.com/google/volley.git 
git clone https://github.com/pmd/pmd.git 
git clone https://github.com/AntennaPod/AntennaPod.git 
git clone https://github.com/ZHENFENG13/spring-boot-projects.git 
git clone https://github.com/google/hover.git 
git clone https://github.com/500px/500px-android-blur.git 
git clone https://github.com/natario1/CameraView.git 
git clone https://github.com/ZieIony/Carbon.git 
git clone https://github.com/undertow-io/undertow.git 
git clone https://github.com/aragozin/jvm-tools.git 
git clone https://github.com/intuit/karate.git 
git clone https://github.com/FinalTeam/RxGalleryFinal.git 
git clone https://github.com/harjot-oberai/MusicDNA.git
git clone https://github.com/networknt/light-4j.git 
git clone https://github.com/florent37/DiagonalLayout.git 
git clone https://github.com/runelite/runelite.git 
git clone https://github.com/CrawlScript/WebCollector.git 
git clone https://github.com/immutables/immutables.git 
git clone https://github.com/AweiLoveAndroid/CommonDevKnowledge.git 
git clone https://github.com/ltsopensource/light-task-scheduler.git 
git clone https://github.com/johannilsson/android-pulltorefresh.git 
git clone https://github.com/code4craft/tiny-spring.git 
git clone https://github.com/spockframework/spock.git
git clone https://github.com/googlearchive/android-Camera2Basic.git 
git clone https://github.com/querydsl/querydsl.git 
git clone https://github.com/googlesamples/google-services.git 
git clone https://github.com/flavioarfaria/KenBurnsView.git 
git clone https://github.com/pchmn/MaterialChipsInput.git 
git clone https://github.com/nisrulz/sensey.git 
git clone https://github.com/romainguy/ViewServer.git 
git clone https://github.com/aritraroy/PatternLockView.git 
git clone https://github.com/saulmm/Material-Movies.git 
git clone https://github.com/siyamed/android-shape-imageview.git
git clone https://github.com/sd6352051/NiftyDialogEffects.git 
git clone https://github.com/balysv/material-menu.git 
git clone https://github.com/Cleveroad/SlidingTutorial-Android.git 
git clone https://github.com/huazhiyuan2008/RecyclerViewCardGallery.git 
git clone https://github.com/ozodrukh/CircularReveal.git 
git clone https://github.com/vert-x3/vertx-examples.git 
git clone https://github.com/githubwing/ZoomHeader.git 
git clone https://github.com/Polidea/RxAndroidBle.git 
git clone https://github.com/path/android-priority-jobqueue.git 
git clone https://github.com/LWJGL/lwjgl3.git 
git clone https://github.com/simple-android-framework/android_design_patterns_analysis.git 
git clone https://github.com/jboss-javassist/javassist.git 
git clone https://github.com/Comcast/FreeFlow.git 
git clone https://github.com/NLPIR-team/NLPIR.git 
git clone https://github.com/amitshekhariitbhu/awesome-android-complete-reference.git 
git clone https://github.com/promeG/TinyPinyin.git 
git clone https://github.com/ethanhua/Skeleton.git 
git clone https://github.com/JackyAndroid/AndroidTVLauncher.git 
git clone https://github.com/chanjarster/weixin-java-tools.git 
git clone https://github.com/lisawray/groupie.git 
git clone https://github.com/dlew/joda-time-android.git 
git clone https://github.com/pnikosis/materialish-progress.git 
git clone https://github.com/JakeWharton/Telecine.git 
git clone https://github.com/watabou/pixel-dungeon.git
git clone https://github.com/jjoe64/GraphView.git 
git clone https://github.com/AbrahamCaiJin/CommonUtilLibrary.git 
git clone https://github.com/plantuml/plantuml.git 
git clone https://github.com/apache/kylin.git 
git clone https://github.com/LuckyJayce/ViewPagerIndicator.git 
git clone https://github.com/Meituan-Dianping/Leaf.git 
git clone https://github.com/huburt-Hu/NewbieGuide.git 
git clone https://github.com/r0adkll/Slidr.git
git clone https://github.com/iPaulPro/Android-ItemTouchHelper-Demo.git 
git clone https://github.com/liuyubobobo/Play-with-Algorithms.git 
git clone https://github.com/deano2390/MaterialShowcaseView.git 
git clone https://github.com/jiajunhui/PlayerBase.git 
git clone https://github.com/esoxjem/MovieGuide.git 
git clone https://github.com/ldoublem/LoadingView.git 
git clone https://github.com/baidu/uid-generator.git 
git clone https://github.com/facebook/device-year-class.git 
git clone https://github.com/javaee-samples/javaee7-samples.git 
git clone https://github.com/Twitter4J/Twitter4J.git 
git clone https://github.com/apache/incubator-pinot.git 
git clone https://github.com/jaydenxiao2016/AndroidFire.git 
git clone https://github.com/mxn21/FlowingDrawer.git 
git clone https://github.com/konifar/android-material-design-icon-generator-plugin.git 
git clone https://github.com/spring-projects/spring-loaded.git 
git clone https://github.com/2227324689/gpmall.git 
git clone https://github.com/Red5/red5-server.git 
git clone https://github.com/stylefeng/Guns.git 
git clone https://github.com/bm-x/PhotoView.git 
git clone https://github.com/florent37/ViewAnimator.git 
git clone https://github.com/javagrowing/JGrowing.git 
git clone https://github.com/prontera/spring-cloud-rest-tcc.git 
git clone https://github.com/M66B/NetGuard.git 
git clone https://github.com/szerhusenBC/jwt-spring-security-demo.git 
git clone https://github.com/bingoogolapple/BGABadgeView-Android.git 
git clone https://github.com/citerus/dddsample-core.git 
git clone https://github.com/ata4/disunity.git 
git clone https://github.com/2dxgujun/AndroidTagGroup.git 
git clone https://github.com/MindorksOpenSource/PRDownloader.git 
git clone https://github.com/yuliskov/SmartYouTubeTV.git 
git clone https://github.com/jdsjlzx/LRecyclerView.git 
git clone https://github.com/android-cjj/JJSearchViewAnim.git 
git clone https://github.com/yingLanNull/ShadowImageView.git 
git clone https://github.com/AltBeacon/android-beacon-library.git 
git clone https://github.com/guolindev/booksource.git 
git clone https://github.com/evrencoskun/TableView.git 
git clone https://github.com/square/tape.git 
git clone https://github.com/java8/Java8InAction.git 
git clone https://github.com/jamesdbloom/mockserver.git 
git clone https://github.com/wildfly/wildfly.git 
git clone https://github.com/VictorAlbertos/RxCache.git 
git clone https://github.com/fengjundev/Android-Skin-Loader.git 
git clone https://github.com/sockeqwe/AdapterDelegates.git 
git clone https://github.com/gouthampradhan/leetcode.git 
git clone https://github.com/voldemort/voldemort.git 
git clone https://github.com/flowable/flowable-engine.git 
git clone https://github.com/tyzlmjj/PagerBottomTabStrip.git 
git clone https://github.com/katzer/cordova-plugin-local-notifications.git 
git clone https://github.com/xmuSistone/CardSlidePanel.git 
git clone https://github.com/daimajia/AnimationEasingFunctions.git 
git clone https://github.com/qiujuer/Genius-Android.git 
git clone https://github.com/zhouchaoyuan/excelPanel.git 
git clone https://github.com/tronprotocol/java-tron.git 
git clone https://github.com/alibaba/transmittable-thread-local.git 
git clone https://github.com/getActivity/AndroidProject.git 
git clone https://github.com/Zomato/AndroidPhotoFilters.git 
git clone https://github.com/cSploit/android.git 
git clone https://github.com/Frank-Zhu/PullZoomView.git 
git clone https://github.com/debezium/debezium.git 
git clone https://github.com/iammert/MaterialIntroView.git 
git clone https://github.com/yangchong211/LifeHelper.git 
git clone https://github.com/graphhopper/graphhopper.git
git clone https://github.com/chenupt/SpringIndicator.git 
git clone https://github.com/twosigma/beakerx.git 
git clone https://github.com/Dimezis/BlurView.git 
git clone https://github.com/TakuSemba/Spotlight.git 
git clone https://github.com/JakeWharton/RxRelay.git 
git clone https://github.com/Rukey7/MvpApp.git 
git clone https://github.com/zjw-swun/AppMethodOrder.git 
git clone https://github.com/AigeStudio/WheelPicker.git 
git clone https://github.com/balysv/material-ripple.git
git clone https://github.com/vikramkakkar/SublimePicker.git 
git clone https://github.com/h2oai/h2o-2.git 
git clone https://github.com/FasterXML/jackson-databind.git 
git clone https://github.com/line/armeria.git 
git clone https://github.com/theDazzler/droidicon.git 
git clone https://github.com/markushi/android-ui.git 
git clone https://github.com/twitter/distributedlog.git 
git clone https://github.com/brianway/springmvc-mybatis-learning.git 
git clone https://github.com/elye/loaderviewlibrary.git 
git clone https://github.com/Ramotion/paper-onboarding-android.git 
git clone https://github.com/oasisfeng/condom.git 
git clone https://github.com/yqritc/RecyclerView-FlexibleDivider.git 
git clone https://github.com/mongodb/mongo-java-driver.git 
git clone https://github.com/xinghongfei/LookLook.git 
git clone https://github.com/arcadefire/nice-spinner.git 
git clone https://github.com/igreenwood/SimpleCropView.git 
git clone https://github.com/kabouzeid/Phonograph.git 
git clone https://github.com/pwittchen/ReactiveNetwork.git 
git clone https://github.com/florent37/CameraFragment.git 
git clone https://github.com/sucese/android-open-source-project-analysis.git 
git clone https://github.com/mxdldev/android-mvp-mvvm-flytour.git 
git clone https://github.com/florent37/ShapeOfView.git 
git clone https://github.com/microg/android_packages_apps_GmsCore.git 
git clone https://github.com/code-mc/material-icon-lib.git 
git clone https://github.com/grandcentrix/tray.git 
git clone https://github.com/spotify/docker-maven-plugin.git 
git clone https://github.com/Prototik/HoloEverywhere.git 
git clone https://github.com/hefuyicoder/ListenerMusicPlayer.git 
git clone https://github.com/ankidroid/Anki-Android.git 
git clone https://github.com/H07000223/FlycoDialog_Master.git 
git clone https://github.com/Krupen/FabulousFilter.git 
git clone https://github.com/mcxtzhang/ZLayoutManager.git 
git clone https://github.com/EverythingMe/overscroll-decor.git 
git clone https://github.com/Netflix/conductor.git 
git clone https://github.com/Yalantis/Euclid.git 
git clone https://github.com/tiann/understand-plugin-framework.git 
git clone https://github.com/apache/rocketmq-externals.git 
git clone https://github.com/BaronZ88/MinimalistWeather.git 
git clone https://github.com/Diolor/Swipecards.git 
git clone https://github.com/yanzhenjie/Album.git 
git clone https://github.com/jackpal/Android-Terminal-Emulator.git 
git clone https://github.com/nutzam/nutz.git 
git clone https://github.com/FudanNLP/fnlp.git 
git clone https://github.com/JessYanCoding/ProgressManager.git 
git clone https://github.com/stormzhang/9GAG.git 
git clone https://github.com/square/mortar.git 
git clone https://github.com/soarcn/BottomSheet.git 
git clone https://github.com/wordpress-mobile/WordPress-Android.git 
git clone https://github.com/LaiFeng-Android/SopCastComponent.git 
git clone https://github.com/android-cjj/BeautifulRefreshLayout.git 
git clone https://github.com/dmilicic/Android-Clean-Boilerplate.git 
git clone https://github.com/jeasonlzy/NineGridView.git 
git clone https://github.com/mik3y/usb-serial-for-android.git
git clone https://github.com/apache/dubbo-admin.git 
git clone https://github.com/xfumihiro/ViewInspector.git 
git clone https://github.com/jMonkeyEngine/jmonkeyengine.git 
git clone https://github.com/avast/android-styled-dialogs.git 
git clone https://github.com/ballerina-platform/ballerina-lang.git 
git clone https://github.com/android-cjj/BeautifulRefreshLayout.git 
git clone https://github.com/LaiFeng-Android/SopCastComponent.git 
git clone https://github.com/CyC2018/CS-Notes.git 
git clone https://github.com/Snailclimb/JavaGuide.git 
git clone https://github.com/iluwatar/java-design-patterns.git 
git clone https://github.com/MisterBooo/LeetCodeAnimation.git
git clone https://github.com/kdn251/interviews.git 
git clone https://github.com/apache/commons-math.git 
git clone https://github.com/apache/commons-io.git 
git clone https://github.com/doocs/advanced-java.git
